services:
  database:
    build: 
      context: ./Database
      dockerfile: Containerfile
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./JAXRS
      dockerfile: Containerfile
    expose:
      - 8080
    ports:
      - "8080:8080"

  web:
    build: 
      context: ./Web
      dockerfile: Containerfile
    links:
      - backend
    ports:
      - "1025:8080"
